name: gameon
description: A Persian-first gaming companion with real game data.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.7
  dio: ^5.7.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  shamsi_date: ^1.1.1
  xml: ^7.0.1
  url_launcher: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
